project:
  type: website
  output-dir: docs
website:
  navbar:
    title: "OpenPlains Learning"
    background: primary
    favicon: content/images/openplains-logo.svg
    twitter-card: true
    open-graph: true
    site-url: https://learning.openplains.com
    search: true
    google-analytics: 
      tracking-id: "G-HDN65TH0DF"
      version: "gtag"
    cookie-consent:
      policy-url: "https://openplains.com/privacy"
      prefs-text: "Cookie Preferences"		
    left:
      - text: "Home"
        href: index.qmd
    tools:
      - icon: github
        menu: 
          - text: "Source Code"
            href: "https://github.com/OpenPlainsInc/openplainsinc.github.io/"
          - text: "Report an Issue"
            href: "https://github.com/OpenPlainsInc/openplainsinc.github.io/issues"

execute:
  freeze: auto
format:
  html:
    theme: [pandoc, theme.scss]
    toc: true
    toc-title: Table of Contents